### PR TITLE
Add en translations for Delete All feature

### PR DESCRIPTION
**Pull request by wasabigeek**
les translations @celandro

### CODE REVIEW

**Review by celandro — APPROVED** [review]
I feel the delete all warning should be a lot stronger. Maybe add This cannot be reversed! In red?

**Comment by wasabigeek** [comment]
How's this? 😆

**Review by celandro — COMMENTED** [review]
Better. For formatting purpose it should be 2 different translations without the dash

**Comment by wasabigeek** [comment]
@celandro two different translations meaning something like this?
```javascript
// pokebox.json
{
    ...
   deleteAll: "This will delete all Pokemon in your Pokebox, are you sure?"
   ...
}

// common.json
{
    ...
    irreversible: "This cannot be reversed!"
    ...
}
```

**Comment by celandro** [comment]
Lgtm

**Comment by wasabigeek** [comment]
Sorry, meaning I should follow my previous comment? Or leaves the PR as is (one translation)?

Regards,
Nicholas
________________________________

**Comment by celandro** [comment]
Change sorry. This feature worries me from a support standpoint

**Comment by wasabigeek** [comment]
Worries you as in "I accidentally deleted my Pokebox, can you undo" type of support requests?

I think we can give it a try - people are able to download and backup their boxes if it's very important to them, and we do have a pretty obvious confirmation dialog. If we want to make it even more obvious it could be those "if you want to delete please type 'delete'" dialogs instead?

**Comment by celandro** [comment]
Basically yes, support requests. I already get enough emails about linking
accounts 🙄. We can add as is but if I get too many complaints will need to
think on it

**Review by celandro — APPROVED** [review]

**Comment by celandro** [comment]
Looks good. Be careful with the merge please

**Review by celandro — APPROVED** [review]

**Pull request merged**
